field = [
    {
        'name': 'Старт',
        'owned_by': None,
        'category': None,
        'price': None,
        'pledge': None,
        'buyout': None,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': None,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,

    },
    {
        'name': 'Старая дорога',
        'owned_by': None,
        'category': 'Светло-жёлтый',
        'price': 60,
        'pledge': 30,
        'buyout': 65,
        'build_house_price': 50,
        'build_hotel_price': 50,
        'sell_house_price': 45,
        'sell_hotel_price': 45,
        'houses': None,
        'hotel': None,
        'renta': 2,
        'one_house_renta': 10,
        'two_house_renta': 30,
        'three_house_renta': 90,
        'four_house_renta': 160,
        'hotel_renta': 250,
    },
    {
        'name': 'Казна',
        'owned_by': None,
        'category': None,
        'price': None,
        'pledge': None,
        'buyout': None,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': None,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Главное шоссе',
        'owned_by': None,
        'category': 'Светло-жёлтый',
        'price': 60,
        'pledge': 30,
        'buyout': 65,
        'build_house_price': 50,
        'build_hotel_price': 50,
        'sell_house_price': 45,
        'sell_hotel_price': 45,
        'houses': None,
        'hotel': None,
        'renta': 4,
        'one_house_renta': 20,
        'two_house_renta': 60,
        'three_house_renta': 180,
        'four_house_renta': 320,
        'hotel_renta': 450,
    },
    {
        'name': 'Подоходный налог',
        'owned_by': None,
        'category': None,
        'price': None,
        'pledge': None,
        'buyout': None,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': None,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Западный морской порт',
        'owned_by': None,
        'category': 'Порты',
        'price': 200,
        'pledge': 100,
        'buyout': 150,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': 25,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Аквапарк',
        'owned_by': None,
        'category': 'Жёлтый',
        'price': 100,
        'pledge': 50,
        'buyout': 65,
        'build_house_price': 50,
        'build_hotel_price': 50,
        'sell_house_price': 45,
        'sell_hotel_price': 45,
        'houses': None,
        'hotel': None,
        'renta': 6,
        'one_house_renta': 30,
        'two_house_renta': 90,
        'three_house_renta': 270,
        'four_house_renta': 400,
        'hotel_renta': 550,
    },
    {
        'name': 'Шанс',
        'owned_by': None,
        'category': None,
        'price': None,
        'pledge': None,
        'buyout': None,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': None,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Городской парк',
        'owned_by': None,
        'category': 'Жёлтый',
        'price': 100,
        'pledge': 50,
        'buyout': 65,
        'build_house_price': 50,
        'build_hotel_price': 50,
        'sell_house_price': 45,
        'sell_hotel_price': 45,
        'houses': None,
        'hotel': None,
        'renta': 6,
        'one_house_renta': 30,
        'two_house_renta': 90,
        'three_house_renta': 270,
        'four_house_renta': 400,
        'hotel_renta': 550,
    },
    {
        'name': 'Горнолыжный курорт',
        'owned_by': None,
        'category': 'Жёлтый',
        'price': 120,
        'pledge': 60,
        'buyout': 85,
        'build_house_price': 50,
        'build_hotel_price': 50,
        'sell_house_price': 45,
        'sell_hotel_price': 45,
        'houses': None,
        'hotel': None,
        'renta': 8,
        'one_house_renta': 40,
        'two_house_renta': 100,
        'three_house_renta': 300,
        'four_house_renta': 450,
        'hotel_renta': 600,
    },
    {
        'name': 'Тюрьма',
        'owned_by': None,
        'category': None,
        'price': None,
        'pledge': None,
        'buyout': None,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': None,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Спальный район',
        'owned_by': None,
        'category': 'Зелёный',
        'price': 140,
        'pledge': 70,
        'buyout': 85,
        'build_house_price': 100,
        'build_hotel_price': 100,
        'sell_house_price': 50,
        'sell_hotel_price': 50,
        'houses': None,
        'hotel': None,
        'renta': 10,
        'one_house_renta': 50,
        'two_house_renta': 150,
        'three_house_renta': 450,
        'four_house_renta': 625,
        'hotel_renta': 750,
    },
    {
        'name': 'Электрическая компания',
        'owned_by': None,
        'category': 'Коммунальные службы',
        'price': 150,
        'pledge': 75,
        'buyout': 100,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': 60,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Деловой квартал',
        'owned_by': None,
        'category': 'Зелёный',
        'price': 140,
        'pledge': 70,
        'buyout': 85,
        'build_house_price': 100,
        'build_hotel_price': 100,
        'sell_house_price': 50,
        'sell_hotel_price': 50,
        'houses': None,
        'hotel': None,
        'renta': 10,
        'one_house_renta': 50,
        'two_house_renta': 150,
        'three_house_renta': 450,
        'four_house_renta': 625,
        'hotel_renta': 750,
    },
    {
        'name': 'Торговая площадь',
        'owned_by': None,
        'category': 'Зелёный',
        'price': 160,
        'pledge': 80,
        'buyout': 95,
        'build_house_price': 100,
        'build_hotel_price': 100,
        'sell_house_price': 50,
        'sell_hotel_price': 50,
        'houses': None,
        'hotel': None,
        'renta': 12,
        'one_house_renta': 60,
        'two_house_renta': 180,
        'three_house_renta': 500,
        'four_house_renta': 700,
        'hotel_renta': 900,
    },
    {
        'name': 'Северный морской порт',
        'owned_by': None,
        'category': 'Порты',
        'price': 200,
        'pledge': 100,
        'buyout': 150,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': 25,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Улица Пушкина',
        'owned_by': None,
        'category': 'light-Зелёный',
        'price': 180,
        'pledge': 90,
        'buyout': 120,
        'build_house_price': 100,
        'build_hotel_price': 100,
        'sell_house_price': 50,
        'sell_hotel_price': 50,
        'houses': None,
        'hotel': None,
        'renta': 14,
        'one_house_renta': 70,
        'two_house_renta': 200,
        'three_house_renta': 550,
        'four_house_renta': 750,
        'hotel_renta': 950,
    },
    {
        'name': 'Казна',
        'owned_by': None,
        'category': 'None',
        'price': None,
        'pledge': None,
        'buyout': None,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': None,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Проспект Мира',
        'owned_by': None,
        'category': 'light-Зелёный',
        'price': 180,
        'pledge': 90,
        'buyout': 120,
        'build_house_price': 100,
        'build_hotel_price': 100,
        'sell_house_price': 50,
        'sell_hotel_price': 50,
        'houses': None,
        'hotel': None,
        'renta': 14,
        'one_house_renta': 70,
        'two_house_renta': 200,
        'three_house_renta': 550,
        'four_house_renta': 750,
        'hotel_renta': 950,
    },
    {
        'name': 'Проспект Победы',
        'owned_by': None,
        'category': 'light-Зелёный',
        'price': 200,
        'pledge': 100,
        'buyout': 125,
        'build_house_price': 100,
        'build_hotel_price': 100,
        'sell_house_price': 50,
        'sell_hotel_price': 50,
        'houses': None,
        'hotel': None,
        'renta': 16,
        'one_house_renta': 80,
        'two_house_renta': 220,
        'three_house_renta': 600,
        'four_house_renta': 800,
        'hotel_renta': 1000,
    },
    {
        'name': 'Бесплатная парковка',
        'owned_by': None,
        'category': None,
        'price': None,
        'pledge': None,
        'buyout': None,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': None,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Бар',
        'owned_by': None,
        'category': 'Красный',
        'price': 220,
        'pledge': 110,
        'buyout': 130,
        'build_house_price': 150,
        'build_hotel_price': 150,
        'sell_house_price': 75,
        'sell_hotel_price': 75,
        'houses': None,
        'hotel': None,
        'renta': 18,
        'one_house_renta': 90,
        'two_house_renta': 250,
        'three_house_renta': 700,
        'four_house_renta': 875,
        'hotel_renta': 1050,
    },
    {
        'name': 'Ночной клуб',
        'owned_by': None,
        'category': 'Красный',
        'price': 220,
        'pledge': 110,
        'buyout': 130,
        'build_house_price': 150,
        'build_hotel_price': 150,
        'sell_house_price': 75,
        'sell_hotel_price': 75,
        'houses': None,
        'hotel': None,
        'renta': 18,
        'one_house_renta': 90,
        'two_house_renta': 250,
        'three_house_renta': 700,
        'four_house_renta': 875,
        'hotel_renta': 1050,
    },
    {
        'name': 'Ресторан',
        'owned_by': None,
        'category': 'Красный',
        'price': 240,
        'pledge': 120,
        'buyout': 140,
        'build_house_price': 150,
        'build_hotel_price': 150,
        'sell_house_price': 75,
        'sell_hotel_price': 75,
        'houses': None,
        'hotel': None,
        'renta': 20,
        'one_house_renta': 100,
        'two_house_renta': 300,
        'three_house_renta': 750,
        'four_house_renta': 925,
        'hotel_renta': 1100,
    },
    {
        'name': 'Восточный морской порт',
        'owned_by': None,
        'category': 'Порты',
        'price': 200,
        'pledge': 100,
        'buyout': 150,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': 25,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Компьютеры',
        'owned_by': None,
        'category': 'Розовый',
        'price': 260,
        'pledge': 130,
        'buyout': 150,
        'build_house_price': 150,
        'build_hotel_price': 150,
        'sell_house_price': 75,
        'sell_hotel_price': 75,
        'houses': None,
        'hotel': None,
        'renta': 22,
        'one_house_renta': 110,
        'two_house_renta': 330,
        'three_house_renta': 800,
        'four_house_renta': 975,
        'hotel_renta': 1150,
    },
    {
        'name': 'Интернет',
        'owned_by': None,
        'category': 'Розовый',
        'price': 260,
        'pledge': 130,
        'buyout': 150,
        'build_house_price': 150,
        'build_hotel_price': 150,
        'sell_house_price': 75,
        'sell_hotel_price': 75,
        'houses': None,
        'hotel': None,
        'renta': 22,
        'one_house_renta': 110,
        'two_house_renta': 330,
        'three_house_renta': 800,
        'four_house_renta': 975,
        'hotel_renta': 1150,
    },
    {
        'name': 'Водопроводная компания',
        'owned_by': None,
        'category': 'Коммунальные службы',
        'price': 150,
        'pledge': 75,
        'buyout': 100,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': 60,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Сотовая связь',
        'owned_by': None,
        'category': 'Розовый',
        'price': 260,
        'pledge': 130,
        'buyout': 150,
        'build_house_price': 150,
        'build_hotel_price': 150,
        'sell_house_price': 75,
        'sell_hotel_price': 75,
        'houses': None,
        'hotel': None,
        'renta': 24,
        'one_house_renta': 120,
        'two_house_renta': 360,
        'three_house_renta': 850,
        'four_house_renta': 1025,
        'hotel_renta': 1200,
    },
    {
        'name': 'Отправляйтесь в тюрьму',
        'owned_by': None,
        'category': None,
        'price': None,
        'pledge': None,
        'buyout': None,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': None,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Морские перевозки',
        'owned_by': None,
        'category': 'Синий',
        'price': 300,
        'pledge': 150,
        'buyout': 170,
        'build_house_price': 200,
        'build_hotel_price': 200,
        'sell_house_price': 100,
        'sell_hotel_price': 100,
        'houses': None,
        'hotel': None,
        'renta': 26,
        'one_house_renta': 130,
        'two_house_renta': 390,
        'three_house_renta': 900,
        'four_house_renta': 1105,
        'hotel_renta': 1275,
    },
    {
        'name': 'Железная дорога',
        'owned_by': None,
        'category': 'Синий',
        'price': 300,
        'pledge': 150,
        'buyout': 170,
        'build_house_price': 200,
        'build_hotel_price': 200,
        'sell_house_price': 100,
        'sell_hotel_price': 100,
        'houses': None,
        'hotel': None,
        'renta': 26,
        'one_house_renta': 130,
        'two_house_renta': 390,
        'three_house_renta': 900,
        'four_house_renta': 1105,
        'hotel_renta': 1275,
    },
    {
        'name': 'Авиакомпания',
        'owned_by': None,
        'category': 'Синий',
        'price': 320,
        'pledge': 160,
        'buyout': 185,
        'build_house_price': 200,
        'build_hotel_price': 200,
        'sell_house_price': 100,
        'sell_hotel_price': 100,
        'houses': None,
        'hotel': None,
        'renta': 28,
        'one_house_renta': 150,
        'two_house_renta': 450,
        'three_house_renta': 1000,
        'four_house_renta': 1200,
        'hotel_renta': 1400,
    },
    {
        'name': 'Южный морской порт',
        'owned_by': None,
        'category': 'Порты',
        'price': 200,
        'pledge': 100,
        'buyout': 150,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': 25,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Шанс',
        'owned_by': None,
        'category': None,
        'price': None,
        'pledge': None,
        'buyout': None,
        'build_house_price': None,
        'build_hotel_price': None,
        'sell_house_price': None,
        'sell_hotel_price': None,
        'houses': None,
        'hotel': None,
        'renta': None,
        'one_house_renta': None,
        'two_house_renta': None,
        'three_house_renta': None,
        'four_house_renta': None,
        'hotel_renta': None,
    },
    {
        'name': 'Курортная зона',
        'owned_by': None,
        'category': 'Голубой',
        'price': 350,
        'pledge': 175,
        'buyout': 190,
        'build_house_price': 200,
        'build_hotel_price': 200,
        'sell_house_price': 100,
        'sell_hotel_price': 100,
        'houses': None,
        'hotel': None,
        'renta': 35,
        'one_house_renta': 175,
        'two_house_renta': 500,
        'three_house_renta': 1100,
        'four_house_renta': 1300,
        'hotel_renta': 1500,
    },
    {
        'name': 'Гостиничный комплекс',
        'owned_by': None,
        'category': 'Голубой',
        'price': 400,
        'pledge': 200,
        'buyout': 220,
        'build_house_price': 200,
        'build_hotel_price': 200,
        'sell_house_price': 100,
        'sell_hotel_price': 100,
        'houses': None,
        'hotel': None,
        'renta': 50,
        'one_house_renta': 200,
        'two_house_renta': 600,
        'three_house_renta': 1400,
        'four_house_renta': 1700,
        'hotel_renta': 2000,
    },
]
